### ISSUE TITLE
New Conversation button doesn't always work

### ISSUE THREAD

**Issue by batnom** [Beyond-Better/bb#23]
I have found that hitting the New Conversation button doesn't always create a new conversation.

I found myself doing a manual `bb stop` and `bb start` to work around this whenever I needed a new conversation.

It doesn't look like there are any errors logged to `.bb/api.log` when this occurs, but I didn't check the browser errors apologies.

Will append further information such as browser console logs the next time I experience this.

Experienced on v0.2.2

**Comment by cngarrison** [comment]
This is a known bug; it will be fixed in the upcoming changes to browser interface. 

In the interim, doing a page refresh in the browser will start a new conversation.

**Comment by cngarrison** [comment]
The updated BUI has a working button for New Conversation.
